import QRCode from 'qrcode';
import {CODE,VERSION,initialSession,questions,commentLabels} from './questionnaire.js';
import {shell,esc,demo,client,notice,formURL} from './shared.js';
import {summarize,fmt} from './stats.js';
let selected=CODE,timer,loading=false,sessions=[];
const demoRows=Array.from({length:8},(_,i)=>({id:String(i),ratings:Object.fromEntries(questions.map((q,j)=>[q.id,(i+j)%5===0?2:((i+j)%2?3:4)])),recommend:i===0?'Non':'Oui',before_level:i%2?'Intermédiaire':'Débutant',after_level:i%3?'Avancé':'Intermédiaire',fonction:'',strengths:i===0?'Les exemples concrets et les échanges.':'',improvements:i===1?'Plus de temps pour les exercices.':'',topics:i===2?'Approfondir les procédures ANPDP.':''}));
function login(message=''){clearInterval(timer);shell(`<div class="eyebrow">ESPACE FORMATEUR</div><h1>Les retours,<br>en un regard<span class="red">.</span></h1><section class="section login"><h2>Connexion privée</h2><p>Accès réservé aux formateurs autorisés.</p><form id="login"><label class="field">Adresse e-mail<input type="email" name="email" autocomplete="username" required></label><label class="field">Mot de passe<input type="password" name="password" autocomplete="current-password" required></label><p id="status" role="status">${esc(message)}</p><button ${!client?'disabled':''}>Se connecter</button></form>${!client?'<p>Connexion Supabase à configurer. <a href="?demo=1">Voir la démonstration</a></p>':''}</section>`,true);document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;const f=new FormData(e.target);try{const {error}=await client.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)throw error;await dashboard();}catch{notice('Connexion impossible. Vérifiez vos identifiants et votre autorisation.');button.disabled=false;}};}
async function dashboard(){
 clearInterval(timer);
 if(!demo){const {data:{user},error}=await client.auth.getUser();if(error||!user)return login();const membership=await client.from('trainers').select('user_id').eq('user_id',user.id).maybeSingle();if(membership.error||!membership.data){await client.auth.signOut();return login('Ce compte n’est pas autorisé à consulter les résultats.');}}
 const result=demo?{data:[initialSession]}:await client.from('sessions').select('*').order('created_at',{ascending:false});if(result.error)return login('Impossible de charger les sessions.');sessions=result.data;if(!sessions.some(s=>s.code===selected))selected=sessions[0]?.code||'';
 shell(`<div class="toolbar"><div><div class="eyebrow">TABLEAU DE BORD</div><h1>Écouter. Améliorer<span class="red">.</span></h1></div><button id="logout" class="secondary">${demo?'Quitter la démo':'Se déconnecter'}</button></div><div class="toolbar"><label class="field">Session<select id="session">${sessions.map(s=>`<option value="${esc(s.code)}" ${s.code===selected?'selected':''}>${esc(s.code)} · ${s.is_open?'ouverte':'fermée'}</option>`).join('')}</select></label><button id="refresh" class="secondary">Actualiser</button><button id="toggle" class="secondary" ${demo?'disabled':''}>Ouvrir / fermer la collecte</button></div><p id="status" role="status" aria-live="polite"></p><div id="results"></div><section class="section qr-panel"><div><div class="eyebrow">ACCÈS STAGIAIRES</div><h2>Un scan. Un retour.</h2><p>Scannez le QR code pour évaluer la formation.</p><a id="formlink" target="_blank" rel="noopener"></a><p><button id="download" class="secondary">Télécharger le QR code</button></p></div><canvas id="qr"></canvas></section><details class="section"><summary>Créer une nouvelle session</summary><p>Réutilise exactement le questionnaire PDP, version ${VERSION}. Pour un autre programme, créez une nouvelle version du questionnaire et de sa validation.</p><form id="newsession"><label class="field">Code unique<input name="code" pattern="[A-Z0-9-]{3,80}" required placeholder="RM-PDP-5J-2027"></label><label class="field">Intitulé<input name="title" maxlength="500" required value="${esc(initialSession.title)}"></label><label class="field">Lieu<input name="location" maxlength="200" required></label><label class="field">Dates<input name="dates" maxlength="200" required placeholder="Du 12 au 16 octobre 2026"></label><button ${demo?'disabled':''}>Créer la session</button></form></details>`,true);
 document.querySelector('#logout').onclick=async()=>{clearInterval(timer);if(demo)location.href='./trainer.html';else{await client.auth.signOut();login();}};
 document.querySelector('#session').onchange=async e=>{selected=e.target.value;await refresh();await qr();};document.querySelector('#refresh').onclick=refresh;
 document.querySelector('#toggle').onclick=async()=>{const s=sessions.find(s=>s.code===selected);if(!s)return;const {error}=await client.from('sessions').update({is_open:!s.is_open}).eq('code',selected);if(error)notice('Modification impossible.');else await dashboard();};
 document.querySelector('#newsession').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;const f=new FormData(e.target);const {error}=await client.from('sessions').insert({...initialSession,code:f.get('code'),title:f.get('title'),location:f.get('location'),dates:f.get('dates')});if(error){notice('Création impossible : vérifiez le code et votre connexion.');button.disabled=false;}else{selected=f.get('code');await dashboard();}};
 document.querySelector('#download').onclick=()=>{const a=document.createElement('a');a.href=document.querySelector('#qr').toDataURL('image/png');a.download=`QR-${selected}.png`;a.click();};await refresh();await qr();timer=setInterval(()=>{if(!document.hidden)refresh();},10000);
}
async function qr(){if(!selected)return;const url=formURL(selected);const a=document.querySelector('#formlink');a.href=url;a.textContent=url;try{await QRCode.toCanvas(document.querySelector('#qr'),url,{width:240,margin:4,errorCorrectionLevel:'M',color:{dark:'#00582d',light:'#ffffff'}});}catch{notice('URL trop longue pour générer le QR code.');}}
async function refresh(){if(loading||!selected)return;loading=true;const forCode=selected;try{let rows=[];if(demo)rows=demoRows;else{for(let offset=0;;offset+=1000){const {data,error}=await client.from('responses').select('id,ratings,recommend,before_level,after_level,fonction,strengths,improvements,topics').eq('session_code',forCode).order('id').range(offset,offset+999);if(error)throw error;rows.push(...data);if(data.length<1000)break;}}if(forCode!==selected){loading=false;return refresh();}const s=summarize(rows);document.querySelector('#results').innerHTML=`<div class="metrics"><article><span>Réponses</span><strong>${s.count}</strong></article><article><span>Note globale de la formation</span><strong>${fmt(s.overall)}<small> / 4</small></strong></article><article><span>Recommandation · Oui</span><strong>${fmt(s.recommend,1)}<small> %</small></strong></article></div>${!rows.length?'<p class="empty">Aucune réponse pour cette session. Les résultats apparaîtront après le premier envoi.</p>':''}<div class="dashboard-grid"><section class="section"><h2>Moyennes par section</h2>${s.sections.map(v=>`<div class="average"><span>${esc(v.title)}</span><strong>${fmt(v.average)} / 4</strong><meter min="0" max="4" value="${v.average??0}"></meter></div>`).join('')}<p class="muted">6. Vos commentaires : réponses libres, sans note.</p></section><section class="section"><h2>Niveau avant / après</h2><table><thead><tr><th>Niveau</th><th>Avant</th><th>Après</th></tr></thead><tbody>${s.levels.map(v=>`<tr><td>${v.level}</td><td>${v.before}</td><td>${v.after}</td></tr>`).join('')}</tbody></table><p class="muted">Nombre de participants par niveau déclaré.</p></section></div><section class="section"><h2>Résultats question par question</h2><p class="muted">Répartition : nombre de réponses pour chaque note de 1 à 4.</p><div class="table-scroll"><table><thead><tr><th>Critère</th><th>Moyenne /4</th>${[1,2,3,4].map(v=>`<th>${v}</th>`).join('')}</tr></thead><tbody>${s.questions.map(q=>`<tr><td>${esc(q.label)}</td><td>${fmt(q.average)}</td>${q.distribution.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section><section class="section"><h2>Vos commentaires</h2>${rows.filter(r=>r.fonction||Object.keys(commentLabels).some(k=>r[k])).map(r=>`<article class="comment">${r.fonction?`<p><strong>Fonction (facultatif) :</strong> ${esc(r.fonction)}</p>`:''}${Object.entries(commentLabels).filter(([k])=>r[k]).map(([k,label])=>`<p><strong>${esc(label)}</strong><br>${esc(r[k])}</p>`).join('')}</article>`).join('')||'<p class="muted">Aucun commentaire pour cette session.</p>'}</section>`;notice(`${demo?'Données fictives · ':''}Actualisé à ${new Date().toLocaleTimeString('fr-FR')} · Actualisation toutes les 10 secondes`);}catch{notice('Actualisation impossible. Les derniers résultats restent affichés. Vérifiez votre connexion ou reconnectez-vous.');}finally{loading=false;}}
if(demo)dashboard();else if(client){client.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')login();});client.auth.getSession().then(({data})=>data.session?dashboard():login());}else login();
